import faker from 'faker';



const Datas = [
    {
        id: 0,
        gender: 'Herr',
        name: faker.name.lastName(),
        projektname: 'GPS Driver Tracking App',
        unternehmen: faker.company.companyName(),
        unternehmensArt: faker.company.companySuffix(),
        verwendung: faker.lorem.paragraph(1),
        technologie: 'Freie Hand',
        budget: 150,
        deadLine: '15.11.2020',
        img: './img/software.png',
        status: 'Done',
        projektZiel: faker.lorem.paragraph(1),
        projektErwartung: faker.lorem.paragraph(1),
        inhaltStruktur: faker.lorem.paragraph(1),
        inhalte: faker.lorem.paragraph(1),
        sonstigeInhalte: faker.lorem.paragraph(1),
        projektIdeen: faker.lorem.paragraph(1),
        mockup: '',
        mustHave: faker.lorem.paragraph(1),
        sprachen: 'Englisch, Deutsch',

    },
    {
        id: 1,
        gender: 'Frau',
        name: faker.name.lastName(),
        projektname: 'Taxi app project',
        unternehmen: faker.company.companyName(),
        unternehmensArt: faker.company.companySuffix(),
        verwendung: faker.lorem.paragraph(1),
        technologie: 'Freie Hand',
        budget: 400,
        deadLine: '15.11.2020',
        img: './img/taxi-app.png',
        status: 'Done',
        projektZiel: faker.lorem.paragraph(1),
        projektErwartung: faker.lorem.paragraph(1),
        inhaltStruktur: faker.lorem.paragraph(1),
        inhalte: faker.lorem.paragraph(1),
        sonstigeInhalte: faker.lorem.paragraph(1),
        projektIdeen: faker.lorem.paragraph(1),
        mockup: '',
        mustHave: '',
        sprachen: 'Türkisch, Deutsch',
    },
    {
        id: 2,
        gender: 'Frau',
        name: faker.name.lastName(),
        projektname: 'Build an app for hiring workers for temporary tasks',
        unternehmen: faker.company.companyName(),
        unternehmensArt: faker.company.companySuffix(),
        verwendung: faker.lorem.paragraph(1),
        technologie: 'Freie Hand',
        budget: 1500,
        deadLine: '15.11.2025',
        img: './img/social-mage.png',
        status: 'Done',
        projektZiel: faker.lorem.paragraph(1),
        projektErwartung: faker.lorem.paragraph(1),
        inhaltStruktur: faker.lorem.paragraph(1),
        inhalte: faker.lorem.paragraph(1),
        sonstigeInhalte: faker.lorem.paragraph(1),
        projektIdeen: faker.lorem.paragraph(1),
        mockup: '',
        mustHave: '',
        sprachen: 'Deutsch',
    },
    {
        id: 3,
        gender: 'Frau',
        name: faker.name.lastName(),
        projektname: 'music App to be develop on android only',
        unternehmen: faker.company.companyName(),
        unternehmensArt: faker.company.companySuffix(),
        verwendung: faker.lorem.paragraph(1),
        technologie: 'Freie Hand',
        budget: 350,
        deadLine: '15.11.2025',
        img: './img/chinese-music-app.png',
        status: 'Done',
        projektZiel: faker.lorem.paragraph(1),
        projektErwartung: faker.lorem.paragraph(1),
        inhaltStruktur: faker.lorem.paragraph(1),
        inhalte: faker.lorem.paragraph(1),
        sonstigeInhalte: faker.lorem.paragraph(1),
        projektIdeen: faker.lorem.paragraph(1),
        mockup: faker.lorem.paragraph(1),
        mustHave: faker.lorem.paragraph(1),
        sprachen: faker.lorem.paragraph(1),
    },
];

console.log(Datas)

export default Datas;